# Generated by Django 4.0.3 on 2022-08-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual_pdf',
            name='End_Date',
        ),
        migrations.RemoveField(
            model_name='manual_pdf',
            name='Start_Date',
        ),
        migrations.AlterField(
            model_name='manual_pdf',
            name='Download',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='manuals/'),
        ),
    ]
