# Generated by Django 4.0.3 on 2022-10-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals_app', '0003_manual_backend_delete_manual_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manual_backend',
            name='Description',
            field=models.TextField(default='ici'),
        ),
    ]
