# Generated by Django 3.1 on 2022-10-16 15:51

from django.db import migrations, models
import manuals_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('manuals_app', '0008_auto_20221016_1225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manual',
        ),
        migrations.DeleteModel(
            name='manual_backend',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='Description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=False, upload_to='images'),
        ),
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media', validators=[manuals_app.models.validate_file_extension]),
        ),
    ]
